### ISSUE TITLE
Check/Checklist Management

### ISSUE THREAD

**Issue by garcialo** [garcialo/OATAudit#27]
Create additional issues from the following task list

- [ ] Create check
- [ ] Create checklist from available checks
- [ ] Edit check
- [ ] Edit checklist
- [ ] Delete check
- [ ] Delete checklist 
- [ ] Display *.ts code for creating/updating a check file
- [ ] Display *.ts code for creating/updating a checklist file

Editing check format (i.e. adding authors, history, reference links etc.) is out of scope for this issue.

### Notes:
Checklists reference specific versions of a check
Changing an existing check's description should create a new check (new check_ID)
Checks should track their "previous" and "next" version?
